In [1]:
import cv2
import numpy as np
from smoothing import gaussian_smoothing_kernel
from sharpening import sharpening_kernel
from convolution import apply_convolution
import matplotlib.pyplot as plt

In [2]:
lena = cv2.imread('./Lena.jpg', 1)

cv2.imshow('Original Image', lena)
cv2.waitKey(0)
cv2.destroyAllWindows()

## 2.a: Take an RGB image and apply convolution with each kernel, separately on each channel.


In [3]:
lena_b = lena.copy()
lena_b[:, :, 1] = 0
lena_b[:, :, 2] = 0
print(lena_b.shape)

lena_g = lena.copy()
lena_g[:, :, 0] = 0
lena_g[:, :, 2] = 0
print(lena_g.shape)

lena_r = lena.copy()
lena_r[:, :, 0] = 0
lena_r[:, :, 1] = 0
print(lena_r.shape)


(512, 512, 3)
(512, 512, 3)
(512, 512, 3)


In [4]:
cv2.imshow("Lena Blue Channel", lena_b)
cv2.imshow("Lena Green Channel", lena_g)
cv2.imshow("Lena Red Channel", lena_r)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
bc, gc, rc = cv2.split(lena)

print(bc.shape, gc.shape, rc.shape)

(512, 512) (512, 512) (512, 512)


- Gaussian Smoothing Kernel

In [6]:
smk = gaussian_smoothing_kernel(5, 1.67)

print(smk)

smooth_bc = apply_convolution(bc, smk)
smooth_gc = apply_convolution(gc, smk)
smooth_rc = apply_convolution(rc, smk)

[[0.00687486 0.02015726 0.02885054 0.02015726 0.00687486]
 [0.02015726 0.05910157 0.08459048 0.05910157 0.02015726]
 [0.02885054 0.08459048 0.12107208 0.08459048 0.02885054]
 [0.02015726 0.05910157 0.08459048 0.05910157 0.02015726]
 [0.00687486 0.02015726 0.02885054 0.02015726 0.00687486]]


In [7]:
border_img_bc = smooth_bc["border_img"]
convo_bc = smooth_bc["raw_result"]
norm_bc = smooth_bc["normalized"]
norm_cropped_bc = smooth_bc["final"]

border_img_gc = smooth_gc["border_img"]
convo_gc = smooth_gc["raw_result"]
norm_gc = smooth_gc["normalized"]
norm_cropped_gc = smooth_gc["final"]

border_img_rc = smooth_rc["border_img"]
convo_rc = smooth_rc["raw_result"]
norm_rc = smooth_rc["normalized"]
norm_cropped_rc = smooth_rc["final"]

intermediate = cv2.merge((norm_cropped_bc, norm_cropped_gc, norm_cropped_rc))
final = np.round(cv2.normalize(intermediate, None, 0, 255, cv2.NORM_MINMAX)).astype(np.uint8)

In [8]:
blue_only = np.zeros((norm_cropped_bc.shape[0], norm_cropped_bc.shape[1], 3), dtype=np.uint8)
blue_only[:, :, 0] = 255 
blue_only[:, :, 1] = 255-norm_cropped_bc
blue_only[:, :, 2] = 255-norm_cropped_bc

green_only = np.zeros((norm_cropped_bc.shape[0], norm_cropped_bc.shape[1], 3), dtype=np.uint8)
green_only[:, :, 0] = 255-norm_cropped_gc
green_only[:, :, 1] = 255
green_only[:, :, 2] = 255-norm_cropped_gc

red_only = np.zeros((norm_cropped_bc.shape[0], norm_cropped_bc.shape[1], 3), dtype=np.uint8)
red_only[:, :, 0] = 255-norm_cropped_rc
red_only[:, :, 1] = 255-norm_cropped_rc
red_only[:, :, 2] = 255

test = cv2.merge((norm_cropped_bc, norm_cropped_gc, norm_cropped_rc))

cv2.imshow("Blue Channel Convolution Only", blue_only)
cv2.imshow("Green Channel Convolution Only", green_only)
cv2.imshow("Red Channel Convolution Only", red_only)
cv2.imshow("Original", lena)
cv2.imshow("Final Merged Image", test)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# cv2.imshow("Blue Channel Border", border_img_bc)
# cv2.imshow("Blue Channel Convo", convo_bc)
# cv2.imshow("Blue Channel Norm", norm_bc)
# cv2.imshow("Blue Channel Norm Cropped", norm_cropped_bc)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [10]:
# cv2.imshow("Green Channel Border", border_img_gc)
# cv2.imshow("Green Channel Convo", convo_gc)
# cv2.imshow("Green Channel Norm", norm_gc)
# cv2.imshow("Green Channel Norm Cropped", norm_cropped_gc)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [11]:
# cv2.imshow("Red Channel Border", border_img_rc)
# cv2.imshow("Red Channel Convo", convo_rc)
# cv2.imshow("Red Channel Norm", norm_rc)
# cv2.imshow("Red Channel Norm Cropped", norm_cropped_rc)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [12]:
# cv2.imshow("Real", lena)
# cv2.imshow("Final Merged Image", final)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

- Gaussian Sharpening (LoG) Kernel

In [13]:
bc2, gc2, rc2 = cv2.split(lena)

In [14]:
shk = sharpening_kernel(7, 1.67)

print(shk)

sh_bc = apply_convolution(bc2, shk)
sh_gc = apply_convolution(gc2, shk)
sh_rc = apply_convolution(rc2, shk)

[[ 0.06336218  0.09278345  0.09465858  0.08763715  0.09465858  0.09278345
   0.06336218]
 [ 0.09278345  0.07420858 -0.03031136 -0.09902414 -0.03031136  0.07420858
   0.09278345]
 [ 0.09465858 -0.03031136 -0.32138653 -0.49195987 -0.32138653 -0.03031136
   0.09465858]
 [ 0.08763715 -0.09902414 -0.49195987 -0.71712862 -0.49195987 -0.09902414
   0.08763715]
 [ 0.09465858 -0.03031136 -0.32138653 -0.49195987 -0.32138653 -0.03031136
   0.09465858]
 [ 0.09278345  0.07420858 -0.03031136 -0.09902414 -0.03031136  0.07420858
   0.09278345]
 [ 0.06336218  0.09278345  0.09465858  0.08763715  0.09465858  0.09278345
   0.06336218]]


In [15]:
border_img_bc_2 = sh_bc["border_img"]
convo_bc_2 = sh_bc["raw_result"]
norm_bc_2 = sh_bc["normalized"]
norm_cropped_bc_2 = sh_bc["final"]

border_img_gc_2 = sh_gc["border_img"]
convo_gc_2 = sh_gc["raw_result"]
norm_gc_2 = sh_gc["normalized"]
norm_cropped_gc_2 = sh_gc["final"]

border_img_rc_2 = sh_rc["border_img"]
convo_rc_2 = sh_rc["raw_result"]
norm_rc_2 = sh_rc["normalized"]
norm_cropped_rc_2 = sh_rc["final"]

int2 = cv2.merge((norm_cropped_bc_2, norm_cropped_gc_2, norm_cropped_rc_2))
final2 = np.round(cv2.normalize(int2, None, 0, 255, cv2.NORM_MINMAX)).astype(np.uint8)

In [16]:
bc_edge = cv2.subtract(norm_cropped_rc_2, bc)

test5 = np.zeros((bc_edge.shape[0], bc_edge.shape[1], 3), dtype=np.uint8)
 
test5[:, :, 0] = 255             
test5[:, :, 1] = 255-bc_edge     
test5[:, :, 2] = 255-bc_edge     

cv2.imshow("Blue Edges Grayscale", bc_edge)
cv2.imshow("Blue Edges White Background", test5)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
gc_edge = cv2.subtract(norm_cropped_gc_2, gc)

test6 = np.zeros((gc_edge.shape[0], gc_edge.shape[1], 3), dtype=np.uint8)

test6[:, :, 0] = 255-gc_edge     
test6[:, :, 1] = 255             
test6[:, :, 2] = 255-gc_edge     

cv2.imshow("Green Edges Grayscale", gc_edge)
cv2.imshow("Green Edges White Background", test6)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
rc_edge = cv2.subtract(norm_cropped_bc_2, rc)

test7 = np.zeros((rc_edge.shape[0], rc_edge.shape[1], 3), dtype=np.uint8)

test7[:, :, 0] = 255-rc_edge     
test7[:, :, 1] = 255-rc_edge     
test7[:, :, 2] = 255             

cv2.imshow("Red Edges Grayscale", rc_edge)
cv2.imshow("Red Edges White Background", test7)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [59]:
final_edge = test5 + test6 + test7

cv2.imshow("Final Edge Image", final_edge)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
# cv2.imshow("Blue Channel Border", border_img_bc_2)
# cv2.imshow("Blue Channel Convo", convo_bc_2)
# cv2.imshow("Blue Channel Norm", norm_bc_2)
# cv2.imshow("Blue Channel Norm Cropped", norm_cropped_bc_2)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [21]:
# cv2.imshow("Green Channel Border", border_img_gc_2)
# cv2.imshow("Green Channel Convo", convo_gc_2)
# cv2.imshow("Green Channel Norm", norm_gc_2)
# cv2.imshow("Green Channel Norm Cropped", norm_cropped_gc_2)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [22]:
# cv2.imshow("Red Channel Border", border_img_rc_2)
# cv2.imshow("Red Channel Convo", convo_rc_2)
# cv2.imshow("Red Channel Norm", norm_rc_2)
# cv2.imshow("Red Channel Norm Cropped", norm_cropped_rc_2)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [23]:
# cv2.imshow("Real", lena)
# cv2.imshow("Final Merged Image", final2)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

## 2.b : Convert the RGB image to HSV mode and apply convolution with each kernel, separately on each channel of HSV space.

In [47]:
lena_hsv = cv2.cvtColor(lena, cv2.COLOR_BGR2HSV)

cv2.imshow("Lena HSV", lena_hsv)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [49]:
h, s, v = cv2.split(lena_hsv)

print(h.shape)
print(s.shape)
print(v.shape)

# lena_h = lena_hsv.copy()
# lena_h[:, :, 1] = 0
# lena_h[:, :, 2] = 0

# lena_s = lena_hsv.copy()
# lena_s[:, :, 0] = 0
# lena_s[:, :, 2] = 0

# lena_v = lena_hsv.copy()
# lena_v[:, :, 0] = 0
# lena_v[:, :, 1] = 0

cv2.imshow("Lena H Channel", h)
cv2.imshow("Lena S Channel", s)
cv2.imshow("Lena V Channel", v)

cv2.waitKey(0)
cv2.destroyAllWindows()

(512, 512)
(512, 512)
(512, 512)


- Gaussian Smoothing Kernel

In [50]:
sm_kernel = gaussian_smoothing_kernel(5, 1.67)

print(sm_kernel)

h_sm_convo = apply_convolution(h, sm_kernel)
s_sm_convo = apply_convolution(s, sm_kernel)
v_sm_convo = apply_convolution(v, sm_kernel)

[[0.00687486 0.02015726 0.02885054 0.02015726 0.00687486]
 [0.02015726 0.05910157 0.08459048 0.05910157 0.02015726]
 [0.02885054 0.08459048 0.12107208 0.08459048 0.02885054]
 [0.02015726 0.05910157 0.08459048 0.05910157 0.02015726]
 [0.00687486 0.02015726 0.02885054 0.02015726 0.00687486]]


In [51]:
h_border = h_sm_convo["border_img"]
h_raw = h_sm_convo["raw_result"]
h_norm = h_sm_convo["normalized"]
h_final = h_sm_convo["final"]

s_border = s_sm_convo["border_img"]
s_raw = s_sm_convo["raw_result"]
s_norm = s_sm_convo["normalized"]
s_final = s_sm_convo["final"]

v_border = v_sm_convo["border_img"]
v_raw = v_sm_convo["raw_result"]
v_norm = v_sm_convo["normalized"]
v_final = v_sm_convo["final"]


int3 = cv2.merge([h_final, s_final, v_final])
final_sm = np.round(cv2.normalize(int3, None, 0, 255, cv2.NORM_MINMAX)).astype(np.uint8)

In [ ]:
# h_only = np.zeros((h_final.shape[0], h_final.shape[1], 3), dtype=np.uint8)
# h_only[:, :, 0] = h_final 
# h_only[:, :, 1] = 0
# h_only[:, :, 2] = 0

# s_only = np.zeros((s_final.shape[0], s_final.shape[1], 3), dtype=np.uint8)
# s_only[:, :, 0] = 0
# s_only[:, :, 1] = s_final
# s_only[:, :, 2] = 0

# v_only = np.zeros((v_final.shape[0], v_final.shape[1], 3), dtype=np.uint8)
# v_only[:, :, 0] = 0
# v_only[:, :, 1] = 0
# v_only[:, :, 2] = v_final

# test_hsv = cv2.merge([h_final, s_final, v_final])


In [56]:
cv2.imshow("H Channel Convolution Only", h_final)
cv2.imshow("S Channel Convolution Only", s_final)
cv2.imshow("V Channel Convolution Only", v_final)
cv2.imshow("Original", lena_hsv)
cv2.imshow("Final Merged Image", final_sm)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [30]:
# cv2.imshow("H Border", h_border)
# cv2.imshow("H Raw", h_raw)
# cv2.imshow("H Norm", h_norm)
# cv2.imshow("H Final", h_final)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [31]:
# cv2.imshow("S Border", s_border)
# cv2.imshow("S Raw", s_raw)
# cv2.imshow("S Norm", s_norm)
# cv2.imshow("S Final", s_final)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [32]:
# cv2.imshow("V Border", v_border)
# cv2.imshow("V Raw", v_raw)
# cv2.imshow("V Norm", v_norm)
# cv2.imshow("V Final", v_final)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [33]:
# cv2.imshow("Original HSV", lena_hsv)
# cv2.imshow("Final SM", final_sm)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

- Sharpening Kernel

In [34]:
sh_kernel = sharpening_kernel(7, 1.67)

sh_h_convo = apply_convolution(h, sh_kernel)
sh_s_convo = apply_convolution(s, sh_kernel)
sh_v_convo = apply_convolution(v, sh_kernel)

In [44]:
h_border_sh = sh_h_convo["border_img"]
h_raw_sh = sh_h_convo["raw_result"]
h_norm_sh = sh_h_convo["normalized"]
h_final_sh = sh_h_convo["final"]

s_border_sh = sh_s_convo["border_img"]
s_raw_sh = sh_s_convo["raw_result"]
s_norm_sh = sh_s_convo["normalized"]
s_final_sh = sh_s_convo["final"]

v_border_sh = sh_v_convo["border_img"]
v_raw_sh = sh_v_convo["raw_result"]
v_norm_sh = sh_v_convo["normalized"]
v_final_sh = sh_v_convo["final"]

int4 = cv2.merge([h_final_sh, s_final_sh, v_final_sh])
final_sh = np.round(cv2.normalize(int4, None, 0, 255, cv2.NORM_MINMAX)).astype(np.uint8)

In [ ]:
h_edge = cv2.subtract(h_final_sh, h)
# test_h_edge = np.zeros((h_edge.shape[0], h_edge.shape[1], 3), dtype=np.uint8)

# test_h_edge[:, :, 0] = h_edge
# test_h_edge[:, :, 1] = 0
# test_h_edge[:, :, 2] = 0

s_edge = cv2.subtract(s_final_sh, s)
# test_s_edge = np.zeros((s_edge.shape[0], s_edge.shape[1], 3), dtype=np.uint8)

# test_s_edge[:, :, 0] = 0
# test_s_edge[:, :, 1] = s_edge
# test_s_edge[:, :, 2] = 0

v_edge = cv2.subtract(v_final_sh, v)
# test_v_edge = np.zeros((v_edge.shape[0], v_edge.shape[1], 3), dtype=np.uint8)

# test_v_edge[:, :, 0] = 0
# test_v_edge[:, :, 1] = 0
# test_v_edge[:, :, 2] = v_edge

In [58]:
cv2.imshow("Hue Sharp Edges", h_edge)
cv2.imshow("Hue ShK Convolution", h_final_sh)

cv2.imshow("Saturation Sharp Edge", s_edge)
cv2.imshow("Saturtion ShK convolution", s_final_sh)

cv2.imshow("Value Sharp Edge", v_edge)
cv2.imshow("Value ShK Convolution", v_final_sh)

cv2.imshow("Original HSV", lena_hsv)
cv2.imshow("Final", final_sh)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [38]:
# cv2.imshow("H Border", h_border_sh)
# cv2.imshow("H Raw", h_raw_sh)
# cv2.imshow("H Norm", h_norm_sh)
# cv2.imshow("H Final", h_final_sh)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [39]:
# cv2.imshow("S Border", s_border_sh)
# cv2.imshow("S Raw", s_raw_sh)
# cv2.imshow("S Norm", s_norm_sh)
# cv2.imshow("S Final", s_final_sh)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [40]:
# cv2.imshow("V Border", v_border_sh)
# cv2.imshow("V Raw", v_raw_sh)
# cv2.imshow("V Norm", v_norm_sh)
# cv2.imshow("V Final", v_final_sh)

# cv2.waitKey(0)
# cv2.destroyAllWindows()

In [41]:
# cv2.imshow("Original HSV", lena_hsv)
# cv2.imshow("Final SH", final_sh)

# cv2.waitKey(0)
# cv2.destroyAllWindows()